---
- hosts: all
  become: yes

  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - libpq-dev
          - postgresql
          - postgresql-contrib
          - nginx
          - curl
        state: present
