---
- hosts: all
  become: yes
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=started
